### PR TITLE
Knepley/fix stack

### PR DESCRIPTION
**Pull request by knepley**
This fixes stack push/pop.

### CODE REVIEW

**Comment by knepley** [comment]
@baagaard-usgs Two of the builds failed, but I could not see a log, to I restarted them.

**Comment by knepley** [comment]
@baagaard-usgs Okay, I found out how to see the log. It is failing because it is using the wrong PETSc branch. How do we update that?

**Comment by baagaard-usgs** [comment]
We want it to be using `knepley/pylith`. The debian build failed because `main` has the old fault integration. Let me try incorporating your fix into my branch.

**Comment by baagaard-usgs** [comment]
Included in #347

**Pull request closed without merging**
