### PR TITLE
Willic3/docs viscoelasticity

### PR DESCRIPTION
**Pull request by willic3**
Finished documentation for Jacobian. Some of the missing info will be included in the elasticity section.

### CODE REVIEW

**Review by baagaard-usgs — CHANGES_REQUESTED** [review]
Review Part 1

1. A bunch of files in `doc/userguide` got added. None of these should be in the repo. These include `tmp.txt`, `userguide.aux`, etc.
2. The file `sheartraction_disp.spatialdb` in `tests/fullscale/linearelasticity/nofaults-2d` should _not_ be in the repo. It is generated automatically by a Python script during the test.

These updates should be done via rebasing and editing the commit https://github.com/geodynamics/pylith/pull/438/commits/abe7eb205e013c91d353d71d83e6581efaa7f75b to remove these files.

**Comment by willic3** [comment]
I think I've removed all the files that accidentally got committed.

**Review by baagaard-usgs — CHANGES_REQUESTED** [review]
Please check `powerlaw.md`. There was a duplicate equation label `eqn:powerlaw:flowlaw:components`. I made the second one `eqn:powerlaw:flowlaw:components2`, but I didn't update any cross references.

Note: I rebased on the current `main` so you will need to delete your local branch before pulling in the current version of this branch.

**Review by baagaard-usgs — APPROVED** [review]
Cleaned up history.

**Pull request merged**
