### PR TITLE
Ij test rebase

### PR DESCRIPTION
**Pull request by rwalkerlewis**
This branch provides a preliminary injection/point source capability.

### CODE REVIEW

**Comment by baagaard-usgs** [comment]
If this is just a test, then please close. If this is a real pull request then please use rebase to revise with more meaningful commit comments. It is impossible to tell what functionality is being implemented in each step. I recommend squashing and reordering as necessary to create a history that someone else can follow.

**Comment by rwalkerlewis** [comment]
Does this commit message look any better?

**Comment by baagaard-usgs** [comment]
Something got messed up when you rebased. A bunch of commits already in `main` from others got included.

The commit message you now have is acceptable.

Ideally, we want 6+ commits with something like:

1. Add C++ implementation of wellbore source.
2. Implement libtests for wellbore source.
3. Implement MMS test for wellbore source.
3. Add Python/SWIG interface for wellbore source.
4. Implement pytests for wellbore source.
5. Add full-scale test for wellbore source.
6. Add documentation for wellbore source.

**Comment by baagaard-usgs** [comment]
Because this PR is updating the `hackathon/poroelasticity` branch, you need to rebase with respect to `hackathon/poroelasticity` not `main`. Sorry if I confused you. This should get rid of the extra commits.

**Comment by rwalkerlewis** [comment]
Rebased onto hackathon/poroelasticity

**Comment by baagaard-usgs** [comment]
There are still a bunch of extra commits from main that shouldn't be in the PR. You may have to remove them manually when rebasing.

**Comment by rwalkerlewis** [comment]
now?

**Review by baagaard-usgs — CHANGES_REQUESTED** [review]
Thanks for fixing random typos in the code!

Please remove the changes to `.vscode/settings.json`.

I don't see any differences between `pylith/sources/PointsList.py` and `pylith/meshio/PointsList.py`. Why not just use the one in meshio?

I think you need to remove `Material` from `pylith/sources/__init__.py`.

**Comment by rwalkerlewis** [comment]
do you mean changing the __init__.py in sources to point to the PointsList.py in meshio?

**Comment by baagaard-usgs** [comment]
Why have `pylith/sources/PointsList.py` at all? In pylith/sources/Source.py, instead of importing PointsList.py from `pylith/sorces/PointsList.py` why not just import the one in `pylith/meshio/PointsList.py`?

**Comment by rwalkerlewis** [comment]
I saw no other file using this sort of approach, and expected to screw it up somehow....

**Review by baagaard-usgs — APPROVED** [review]

**Pull request merged**
