### PR TITLE
Configure: Update to PETSc 3.14

### PR DESCRIPTION
**Pull request by knepley**

### CODE REVIEW

**Comment by baagaard-usgs** [comment]
We are getting `libtest/meshio` failures showing that fields are being created over cohesive cell entities.

PETSc no longer distinguishes between "normal" cells and "hybrid" cells. When we create fields, we need to make sure we don't end up putting values on cohesive cell entities.

## Solution

Replace NULL arg in call to DMSetField() in Field::subfieldsSetup() with label for non-fault stuff.

Create label for non-fault cells. Follow code used to censor fault cells in DataWriterHDF5.

## Summary of code changes

* Added [`pylith::topology::MeshOps::isCohesiveCell()`](https://github.com/geodynamics/pylith/blob/knepley/update-petsc-3.14/libsrc/pylith/topology/MeshOps.cc#L252) to check whether a cell is a cohesive cell. Replace all instances of code doing this with calls to `MeshOps::isCohesiveCell()`.
* Added [`pylith::topology::MeshOps::getLabelNoFault()`](https://github.com/geodynamics/pylith/blob/knepley/update-petsc-3.14/libsrc/pylith/topology/MeshOps.cc#L217) to get label over non-fault cells (creating it if necessary).
* Adjusted [`pylith::topology::Field::subfieldsSetup()`](https://github.com/geodynamics/pylith/blob/knepley/update-petsc-3.14/libsrc/pylith/topology/Field.cc#L1037) to define field over label.

## Update

This solution works for fields with basis order 0 defined on domain (volume or surface) cells. Sections for fields with basis order 1 (aka fields over vertices) or fields over submeshes are empty (no values).

## Tests

The best tests to use for debugging are the `tests/libtests/meshio` tests, because we create fields over several different entities.

**Comment by baagaard-usgs** [comment]
## Update

Remove `MeshOps::getLabelNoFault()`. Use `DMSetFieldAvoidTensor()`, which Matt added to PETSc.

The Lagrange multiplier field is now not created correctly. All points have a dimension of 0.

## Test case

1. Delete your current knepley/update-petsc-3.14 branch and check it out again.
2. Update PETSc and PyLith.
3. Rebuild. 

```
cd tests/mmstests/faults
make test_faultkin
.libs/test_faultkin --tests=pylith::mmstests::TestFaultKin2D_RigidBlocksStatic_TriP1::testDiscretization >& log
```

### Section output

We expect Field 1 (Lagrange multiplier) to have dim == 2 for the Lagrange multiplier DOF.

```
Viewing field 'solution' Solution field.
  Subfields:
    Subfield displacement, index: 0, components: displacement_x displacement_y, scale: 1000, basisOrder: 1, quadOrder: 1, dimension: -1, cellBasis: simplex
    Subfield lagrange_multiplier_fault, index: 1, components: lagrange_multiplier_fault_x lagrange_multiplier_fault_y, scale: 2.25e+10, basisOrder: 1, quadOrder: 1, dimension: 1, cellBasis: simplex
  dimensionalize flag: 0
DM Object: solution_global 1 MPI processes
  type: plex
solution_global in 2 dimensions:
  0-cells: 12
  1-cells: 21 (3)
  2-cells: 10 (2)
Labels:
  celltype: 5 strata with value/size (0 (12), 1 (18), 3 (8), 2 (3), 5 (2))
  depth: 3 strata with value/size (0 (12), 1 (21), 2 (10))
  material-id: 2 strata with value/size (24 (8), 100 (2))
  boundary: 1 strata with value/size (1 (10))
  fault: 1 strata with value/size (1 (10))
  vtk: 1 strata with value/size (1 (8))
  ghost: 1 strata with value/size (1 (11))
  cohesive interface: 1 strata with value/size (1 (2))
Field displacement:
  adjacency FEM
Field lagrange_multiplier_fault:
  Label 'cohesive interface':
    Index has been calculated in [8, 10)
  [0]: 8 (1)
  [0]: 9 (1)
  adjacency FEM
PetscSection Object: 1 MPI processes
  type not yet set
2 fields
  field 0 with 2 components
Process 0:
  (   0) dim  0 offset   0
  (   1) dim  0 offset   0
  (   2) dim  0 offset   0
  (   3) dim  0 offset   0
  (   4) dim  0 offset   0
  (   5) dim  0 offset   0
  (   6) dim  0 offset   0
  (   7) dim  0 offset   0
  (   8) dim  0 offset   0
  (   9) dim  0 offset   0
  (  10) dim  2 offset   0 constrained 0 1
  (  11) dim  2 offset   2 constrained 0 1
  (  12) dim  2 offset   4 constrained 0 1
  (  13) dim  2 offset   6
  (  14) dim  2 offset   8
  (  15) dim  2 offset  10
  (  16) dim  2 offset  12 constrained 0 1
  (  17) dim  2 offset  14 constrained 0 1
  (  18) dim  2 offset  16 constrained 0 1
  (  19) dim  2 offset  18
  (  20) dim  2 offset  20
  (  21) dim  2 offset  22
  (  22) dim  0 offset  24
  (  23) dim  0 offset  24
  (  24) dim  0 offset  24
  (  25) dim  0 offset  24
  (  26) dim  0 offset  24
  (  27) dim  0 offset  24
  (  28) dim  0 offset  24
  (  29) dim  0 offset  24
  (  30) dim  0 offset  24
  (  31) dim  0 offset  24
  (  32) dim  0 offset  24
  (  33) dim  0 offset  24
  (  34) dim  0 offset  24
  (  35) dim  0 offset  24
  (  36) dim  0 offset  24
  (  37) dim  0 offset  24
  (  38) dim  0 offset  24
  (  39) dim  0 offset  24
  (  40) dim  0 offset  24
  (  41) dim  0 offset  24
  (  42) dim  0 offset  24
  field 1 with 2 components
Process 0:
  (   0) dim  0 offset   0
  (   1) dim  0 offset   0
  (   2) dim  0 offset   0
  (   3) dim  0 offset   0
  (   4) dim  0 offset   0
  (   5) dim  0 offset   0
  (   6) dim  0 offset   0
  (   7) dim  0 offset   0
  (   8) dim  0 offset   0
  (   9) dim  0 offset   0
  (  10) dim  0 offset   2
  (  11) dim  0 offset   4
  (  12) dim  0 offset   6
  (  13) dim  0 offset   8
  (  14) dim  0 offset  10
  (  15) dim  0 offset  12
  (  16) dim  0 offset  14
  (  17) dim  0 offset  16
  (  18) dim  0 offset  18
  (  19) dim  0 offset  20
  (  20) dim  0 offset  22
  (  21) dim  0 offset  24
  (  22) dim  0 offset  24
  (  23) dim  0 offset  24
  (  24) dim  0 offset  24
  (  25) dim  0 offset  24
  (  26) dim  0 offset  24
  (  27) dim  0 offset  24
  (  28) dim  0 offset  24
  (  29) dim  0 offset  24
  (  30) dim  0 offset  24
  (  31) dim  0 offset  24
  (  32) dim  0 offset  24
  (  33) dim  0 offset  24
  (  34) dim  0 offset  24
  (  35) dim  0 offset  24
  (  36) dim  0 offset  24
  (  37) dim  0 offset  24
  (  38) dim  0 offset  24
  (  39) dim  0 offset  24
  (  40) dim  0 offset  24
  (  41) dim  0 offset  24
  (  42) dim  0 offset  24
```

**Comment by knepley** [comment]
@baagaard I found the problem. The label must contain everything that a dof can lie on. I call DMLabelComplete() on my test label.

**Comment by baagaard-usgs** [comment]
Using `DMPlexCompleteLabel()` for my label with the cohesive cells...

Close but not quite. With a basis order of 1, I get dim == 2 at 9 points. I think it should be 3 points because there are 3 hybrid edges between 3 vertices on each side of the fault.

## Updated test output

```
Viewing field 'solution' Solution field.
  Subfields:
    Subfield displacement, index: 0, components: displacement_x displacement_y, scale: 1000, basisOrder: 1, quadOrder: 1, dimension: -1, cellBasis: simplex
    Subfield lagrange_multiplier_fault, index: 1, components: lagrange_multiplier_fault_x lagrange_multiplier_fault_y, scale: 2.25e+10, basisOrder: 1, quadOrder: 1, dimension: 1, cellBasis: simplex
  dimensionalize flag: 0
DM Object: solution_global 1 MPI processes
  type: plex
solution_global in 2 dimensions:
  0-cells: 12
  1-cells: 21 (3)
  2-cells: 10 (2)
Labels:
  celltype: 5 strata with value/size (0 (12), 1 (18), 3 (8), 2 (3), 5 (2))
  depth: 3 strata with value/size (0 (12), 1 (21), 2 (10))
  material-id: 2 strata with value/size (24 (8), 100 (2))
  boundary: 1 strata with value/size (1 (10))
  fault: 1 strata with value/size (1 (10))
  vtk: 1 strata with value/size (1 (8))
  ghost: 1 strata with value/size (1 (11))
  cohesive interface: 1 strata with value/size (1 (15))
Field displacement:
  adjacency FEM
Field lagrange_multiplier_fault:
  Label 'cohesive interface':
    Index has been calculated in [8, 43)
  [0]: 8 (1)
  [0]: 9 (1)
  [0]: 13 (1)
  [0]: 14 (1)
  [0]: 15 (1)
  [0]: 19 (1)
  [0]: 20 (1)
  [0]: 21 (1)
  [0]: 25 (1)
  [0]: 29 (1)
  [0]: 38 (1)
  [0]: 39 (1)
  [0]: 40 (1)
  [0]: 41 (1)
  [0]: 42 (1)
  adjacency FEM
PetscSection Object: 1 MPI processes
  type not yet set
2 fields
  field 0 with 2 components
Process 0:
  (   0) dim  0 offset   0
  (   1) dim  0 offset   0
  (   2) dim  0 offset   0
  (   3) dim  0 offset   0
  (   4) dim  0 offset   0
  (   5) dim  0 offset   0
  (   6) dim  0 offset   0
  (   7) dim  0 offset   0
  (   8) dim  0 offset   0
  (   9) dim  0 offset   0
  (  10) dim  2 offset   0 constrained 0 1
  (  11) dim  2 offset   2 constrained 0 1
  (  12) dim  2 offset   4 constrained 0 1
  (  13) dim  2 offset   6
  (  14) dim  2 offset  10
  (  15) dim  2 offset  14
  (  16) dim  2 offset  18 constrained 0 1
  (  17) dim  2 offset  20 constrained 0 1
  (  18) dim  2 offset  22 constrained 0 1
  (  19) dim  2 offset  24
  (  20) dim  2 offset  28
  (  21) dim  2 offset  32
  (  22) dim  0 offset  36
  (  23) dim  0 offset  36
  (  24) dim  0 offset  36
  (  25) dim  0 offset  36
  (  26) dim  0 offset  36
  (  27) dim  0 offset  36
  (  28) dim  0 offset  36
  (  29) dim  0 offset  36
  (  30) dim  0 offset  36
  (  31) dim  0 offset  36
  (  32) dim  0 offset  36
  (  33) dim  0 offset  36
  (  34) dim  0 offset  36
  (  35) dim  0 offset  36
  (  36) dim  0 offset  36
  (  37) dim  0 offset  36
  (  38) dim  0 offset  36
  (  39) dim  0 offset  36
  (  40) dim  0 offset  36
  (  41) dim  0 offset  38
  (  42) dim  0 offset  40
  field 1 with 2 components
Process 0:
  (   0) dim  0 offset   0
  (   1) dim  0 offset   0
  (   2) dim  0 offset   0
  (   3) dim  0 offset   0
  (   4) dim  0 offset   0
  (   5) dim  0 offset   0
  (   6) dim  0 offset   0
  (   7) dim  0 offset   0
  (   8) dim  0 offset   0
  (   9) dim  0 offset   0
  (  10) dim  0 offset   2
  (  11) dim  0 offset   4
  (  12) dim  0 offset   6
  (  13) dim  2 offset   8
  (  14) dim  2 offset  12
  (  15) dim  2 offset  16
  (  16) dim  0 offset  20
  (  17) dim  0 offset  22
  (  18) dim  0 offset  24
  (  19) dim  2 offset  26
  (  20) dim  2 offset  30
  (  21) dim  2 offset  34
  (  22) dim  0 offset  36
  (  23) dim  0 offset  36
  (  24) dim  0 offset  36
  (  25) dim  0 offset  36
  (  26) dim  0 offset  36
  (  27) dim  0 offset  36
  (  28) dim  0 offset  36
  (  29) dim  0 offset  36
  (  30) dim  0 offset  36
  (  31) dim  0 offset  36
  (  32) dim  0 offset  36
  (  33) dim  0 offset  36
  (  34) dim  0 offset  36
  (  35) dim  0 offset  36
  (  36) dim  0 offset  36
  (  37) dim  0 offset  36
  (  38) dim  0 offset  36
  (  39) dim  0 offset  36
  (  40) dim  2 offset  36
  (  41) dim  2 offset  38
  (  42) dim  2 offset  40
...
Discrete System with 1 fields
    cell total dim 6 total comp 2
  Field displacement FEM2 components (implicit) (Nq 4 Nqc 1)
    PetscFE Object: displacement 1 MPI processes
      type: basic
      Basic Finite Element in 2 dimensions with 2 components
      PetscSpace Object: displacement 1 MPI processes
        type: poly
        Space in 2 variables with 2 components, size 6
        Polynomial space of degree 1
      PetscDualSpace Object: displacement 1 MPI processes
        type: lagrange
        Dual space with 2 components, size 6
        Continuous Lagrange dual space
        Quadrature of order 3 on 4 points (dim 2)
    Boundary boundary (boundary) ESSENTIAL
      components: 0, 1
      ids: 1
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Nonconforming object sizes
[0]PETSC ERROR: The section point (0) closure size 8 != dual space dimension 6
[0]PETSC ERROR: See https://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Development GIT revision: v3.14-201-g87ebeec971  GIT Date: 2020-10-22 06:39:33 -0400
[0]PETSC ERROR: .libs/test_faultkin on a arch-clang-3.6.0_debug named igskcicgltgm067 by baagaard Thu Oct 22 15:11:28 2020
[0]PETSC ERROR: Configure options --PETSC_ARCH=arch-clang-3.6.0_debug --with-debugging=1 --with-clanguage=c --with-mpi-compilers=1 --with-shared-libraries=1 --with-64-bit-points=1 --with-large-file-io=1 --with-lgrind=0 --download-chaco=1 --download-parmetis=1 --download-metis=1 --download-triangle --with-blas-lib=/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Versions/Current/libBLAS.dylib --with-lapack-lib=/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Versions/Current/libLAPACK.dylib --download-ml=1 --download-superlu=1 --with-fc=0 --with-hdf5=1 --with-hdf5-include=/Users/baagaard/tools/unix/hdf5-1.10.6/clang-3.6.0/include --with-hdf5-lib=/Users/baagaard/tools/unix/hdf5-1.10.6/clang-3.6.0/lib/libhdf5.dylib --with-zlib=1
[0]PETSC ERROR: #1 DMProjectLocal_Generic_Plex() line 700 in /Users/baagaard/tools/unix/petsc-dev/src/dm/impls/plex/plexproject.c
[0]PETSC ERROR: #2 DMProjectFunctionLabelLocal_Plex() line 853 in /Users/baagaard/tools/unix/petsc-dev/src/dm/impls/plex/plexproject.c
[0]PETSC ERROR: #3 DMProjectFunctionLabelLocal() line 8455 in /Users/baagaard/tools/unix/petsc-dev/src/dm/interface/dm.c
[0]PETSC ERROR: #4 DMProjectFunctionLabel() line 8411 in /Users/baagaard/tools/unix/petsc-dev/src/dm/interface/dm.c
[0]PETSC ERROR: #5 DMComputeExactSolution() line 5709 in /Users/baagaard/tools/unix/petsc-dev/src/dm/interface/dm.c
[0]PETSC ERROR: #6 DMSNESCheckDiscretization() line 1552 in /Users/baagaard/tools/unix/petsc-dev/src/snes/utils/dmplexsnes.c
 : assertion
```

**Comment by knepley** [comment]
@baagaard I force pushed. The test now works for me. We need to only mark the things we want unknowns on, so I only marked tensor cells.

**Comment by baagaard-usgs** [comment]
@knepley Which test is now passing? The MMS tests still fail for me.

```
.libs/test_faultkin --tests=pylith::mmstests::TestFaultKin2D_RigidBlocksStatic_TriP1::testDiscretization
-- snip --
[0]PETSC ERROR: Nonconforming object sizes
[0]PETSC ERROR: The section point (8) closure size 8 != dual space dimension 12
[0]PETSC ERROR: See https://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Development GIT revision: v3.14-201-g87ebeec971  GIT Date: 2020-10-22 06:39:33 -0400
[0]PETSC ERROR: .libs/test_faultkin on a arch-clang-3.6.0_debug named igskcicgltgm067 by baagaard Fri Oct 23 08:57:48 2020
[0]PETSC ERROR: Configure options --PETSC_ARCH=arch-clang-3.6.0_debug --with-debugging=1 --with-clanguage=c --with-mpi-compilers=1 --with-shared-libraries=1 --with-64-bit-points=1 --with-large-file-io=1 --with-lgrind=0 --download-chaco=1 --download-parmetis=1 --download-metis=1 --download-triangle --with-blas-lib=/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Versions/Current/libBLAS.dylib --with-lapack-lib=/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Versions/Current/libLAPACK.dylib --download-ml=1 --download-superlu=1 --with-fc=0 --with-hdf5=1 --with-hdf5-include=/Users/baagaard/tools/unix/hdf5-1.10.6/clang-3.6.0/include --with-hdf5-lib=/Users/baagaard/tools/unix/hdf5-1.10.6/clang-3.6.0/lib/libhdf5.dylib --with-zlib=1
[0]PETSC ERROR: #1 DMProjectLocal_Generic_Plex() line 700 in /Users/baagaard/tools/unix/petsc-dev/src/dm/impls/plex/plexproject.c
[0]PETSC ERROR: #2 DMProjectFunctionLabelLocal_Plex() line 853 in /Users/baagaard/tools/unix/petsc-dev/src/dm/impls/plex/plexproject.c
[0]PETSC ERROR: #3 DMProjectFunctionLabelLocal() line 8455 in /Users/baagaard/tools/unix/petsc-dev/src/dm/interface/dm.c
[0]PETSC ERROR: #4 DMProjectFunctionLabel() line 8411 in /Users/baagaard/tools/unix/petsc-dev/src/dm/interface/dm.c
[0]PETSC ERROR: #5 DMComputeExactSolution() line 5709 in /Users/baagaard/tools/unix/petsc-dev/src/dm/interface/dm.c
[0]PETSC ERROR: #6 DMSNESCheckDiscretization() line 1552 in /Users/baagaard/tools/unix/petsc-dev/src/snes/utils/dmplexsnes.c
```

**Comment by knepley** [comment]
I run .libs/test_faultkin --tests=pylith::mmstests::Tes
tFaultKin2D_RigidBlocksStatic_TriP1::testDiscretization

: OK

OK (1 tests)

**Comment by knepley** [comment]
@baagaard Are you sure it is rebuilt?

**Pull request merged**
