### PR TITLE
Modified fullscale mandel and terzaghi tests to both pass.

### PR DESCRIPTION
**Pull request by rwalkerlewis**
Disabled checks for the trace strain variable, and the resultant tests for displacement and pressure pass.

### CODE REVIEW

**Comment by rwalkerlewis** [comment]
Oops, disregard this PR until i post an update to fix mandel.

**Comment by rwalkerlewis** [comment]
OK, now mandel passes, ready to go.

**Comment by baagaard-usgs** [comment]
@rwalkerlewis The Terzaghi tests failed on TravisCI. It looks like you may have changed the mesh. I had to merge to get updates from the `knepley/feature-petsc-fe` branch and resolve conflicts, so please update your local branch.

**Comment by baagaard-usgs** [comment]
Terzaghi passes. Mandel does not (looks like `meshes.py` needs updating).

**Pull request merged**
