### PR TITLE
Rlwalker/add ts checks

### PR DESCRIPTION
**Pull request by rwalkerlewis**
Converted MMS Residual and Jacobian Taylor Series checks to use TS. Added a corresponding _solutionDot field for their use.

### CODE REVIEW

**Review by baagaard-usgs — CHANGES_REQUESTED** [review]
Please reformat files to using the uncrustify settings in `developer/uncrustify.cfg`. Most of the changes to MMTest.cc are simply undoing correct formatting. There is an uncrustify plug in for VS Code.

This PR fails to compile. Are DMTSCheck* in knepley/pylith?

**Comment by rwalkerlewis** [comment]
Reviewing the uncrustify bit now. My local version of petsc-pylith includes the DMTSCheck* functions. What is the version used for the checks?

**Comment by baagaard-usgs** [comment]
The CI test runner uses knepley/pylith from the PETSc GitLab repository.

**Comment by rwalkerlewis** [comment]
> Please reformat files to using the uncrustify settings in `developer/uncrustify.cfg`. Most of the changes to MMTest.cc are simply undoing correct formatting. There is an uncrustify plug in for VS Code.
> 
> This PR fails to compile. Are DMTSCheck* in knepley/pylith?

@knepley

**Comment by baagaard-usgs** [comment]
@rwalkerlewis The commit history seems to have gotten messed up. It looks like you rebased and then pulled (history indicates a merge) rather than doing a force push after rebasing. Please rebase again and clean up the history.

**Comment by baagaard-usgs** [comment]
Please rebase and consolidate the commits using squash or reword.

**Pull request merged**
