### PR TITLE
Compaction model

### PR DESCRIPTION
**Pull request by rwalkerlewis**
Added ability to iteratively update porosity. This is accomplished by expanding the three field quasistatic formulation to a six field one.

### CODE REVIEW

**Review by baagaard-usgs — CHANGES_REQUESTED** [review]
Remove `*.gz` from .gitignore. People shouldn't be putting .gz files in their source tree.

Remove changes to `.vscode/settings.json`. I shouldn't have to mention this in every PR.

`pylith::materials::IsotropicLinearPoroelasticity::updateKernelConstants`
alpha (time integration parameter) should not be included as a kernel constant. It is already passed to the kernels by PETSc. Additionally, it is not constant (it depends on the time step).

`libsrc/pylith/materials/Poroelasticity.hh`
`libsrc/pylith/materials/RheologyPoroelasticity.cc`
`pylith/materials/Poroelasticity.py`

Rename `updateFields` to `set/getUseStateVars()` and rename `_updateFields` to `_useStateVars`. "Fields" is too general and "update" suggests the method will actually do some updating, not just set a flag indicating that the update should be done.

`pylith/problems/SolnDispPresTracStrainVelPdotTdot.py`
This is such a specific layout of the solution fields that I would simplify the name to something like `SolnPoroelasticityCompaction`.

Rename `SubfieldPressure_t` to `SubfieldPressureDot` for consistency.

`libsrc/pylith/fekernels/Poroelasticity.cc`

Note the naming convention for the indexing variables is `i_camelCase`. The `i_` prefix  is used to differentiate it from iCamelCase which usually corresponds to an index in a loop. Please revert and update.

Line 96
Missing `assert(s);`
Remove `assert(a);` (not used).

Line 183
Missing `assert(s);`

Line 225
Missing `assert(s);`
Missing `assert(s_t);`

Lines 232-233
Is LHS `f0[0]` for both terms? If so, combine into one line.

Line 262
Missing `assert(s);`
Missing `assert(s_t);`

Lines 269-270
Is LHS `f0[0]` for both terms? If so, combine into one line.

`libsrc/pylith/fekernels/IsotropicLinearPoroelasticity.cc`

Line 2379, 2413, 3267, 5716, 5750, 6615
Missing asserts

`materials.tex`
Line 136: "yz" is listed twice. Fix for others too.

Line 442
Remove setting quadrature order all to the same value. This is done by using the problem defaults now.

Line 325

Add some discussion when poroelasticity should be used. Add cross-reference to discussion of physics (drained/undrained in governing equations).

Change `quasi-static` to `quasistatic`.

`poroelasticity.tex`

Line 180 Move `\eqnannotate` outside `\left[` and use \left( \right) instead. Ditto for same equation in update formulation.

Rename `poroelasticity_update` to `poroelasticity_statevars` or `poroelasticity_compaction`.

`poroelasticity_update.tex`

Line 344 Remove () around \Delta t and \dot{phi}.

**Comment by rwalkerlewis** [comment]
I did not [yet] address this:
`pylith/problems/SolnDispPresTracStrainVelPdotTdot.py
This is such a specific layout of the solution fields that I would simplify the name to something like SolnPoroelasticityCompaction.`

It needs to be addressed, but I erred on the side of functionality for now.

Similarly, Further expansion in the manual on the physics of poroelasticity is needed, however I believe this deserves its own branch and PR.

**Review by baagaard-usgs — CHANGES_REQUESTED** [review]
`poroelasticity_update.tex`

Rename `poroelasticity_update.tex` to `poroelasticity_statevars.tex` or `poroelasticity_compaction.tex`.

Line 88 Move \eqnannotate outside \left[ and use \left( \right).

Line 344 Remove () around \Delta t and \dot{phi}.

`libsrc/pylith/materials/Poroelasticity.hh`
`libsrc/pylith/materials/Poroelasticity.cc`
`modulesrc/materials/Poroelasticity.i`
Line 136 of `Poroelasticity.cc` `getUseStateVars()` -> `setUseStateVars()` when setting data member.

`modulesrc/materials/Poroelasticity.i`
`getUseStateVars` -> `useStateVars`
Change property name from "update_fields" to "use_state_variables".

**Comment by rwalkerlewis** [comment]
I believe i addressed this. Nice to have it explained, of course. Will
review again regardless.

**Review by baagaard-usgs — CHANGES_REQUESTED** [review]
Revert changes to `.vscode/settings.json`.

Remove `doc/userguide/userguide.synctex.gz` from the repository.

These superfluous changes seem to be in most of your PRs. Please review your commits and PRs more carefully and look for extraneous files or changes.

**Comment by rwalkerlewis** [comment]
Not sure where those are coming from, however the latter was the reason for a change to gitignore which i was subsequently rebuked for.

**Comment by baagaard-usgs** [comment]
We don't want to flood `.gitignore` with user-specific artifacts, so we keep it to files that are likely to occur on developers machines.

I still see important lines removed from `.vscode/settings.json`. You may have to download the correct file from `main` to restore the missing lines.

**Comment by rwalkerlewis** [comment]
Argh. I just cut and paste the .vscode/settings.json from main and replaced it. Will try again

**Comment by baagaard-usgs** [comment]
I hate to say it, but the `.vscode/settings.json` file is still messed up. It looks like it has 3 copies of the settings. It should look like https://github.com/geodynamics/pylith/blob/main/.vscode/settings.json.

**Review by baagaard-usgs — APPROVED** [review]

**Pull request merged**
