### PR TITLE
Refactor poroelasticty kernels

### PR DESCRIPTION
**Pull request by rwalkerlewis**
First pass at redesigning poroelastic kernels to inline format. Poroelastic tests pass.

### CODE REVIEW

**Review by baagaard-usgs — CHANGES_REQUESTED** [review]
## `IsotropicLinearPoroelasticity.hh`

1. Move MMS kernels to the appropriate MMS test directory. These kernels are specific to a particular MMS test, so they don't belong in the PyLith library.
2. Remove code that is commented out. Only keep it if you know it will be needed in the future; add a comment to make it clear how it will be used in the future.
3. What do you mean by "re-packed solution field"? I don't see where it is getting repacked.
4. There is still a lot of duplicate code for 2D and 3D and implicit and explicit. Can you rewrite the equations so that the body force terms have the same sign for both implicit and explicit cases? Can you use the tensorOps object to combine the 2D and 3D kernels?

**Comment by rwalkerlewis** [comment]
Second attempt at poroelastic kernel refactoring. Agreed that further could be done to simplify implicit / explicit forms, however a decent test problem for the explicit formulation is needed before anything is done there.
Differences between 2D and 3D forms are less now, however could be improved. Arguable how much the extra effort is worth.

Notable exception - implicit porosity update was retained in the original form as there seems to be no way to use the default context function (it looks for the time derivative of pressure and this throws a segfault.) The updated code has been left in, commented out.

**Comment by baagaard-usgs** [comment]
@rwalkerlewis Can you rebase and condense this into 5-10 commits with descriptive commit messages? If you are unsure how to do this, then please provide a list that shows how to consolidate these commits into 5-10 commits and what the messages for the consolidated commits should be.

For example:

## Refactor implicit poroelasticity kernels

```
HASH1 message1
HASH2 message2
HASH3 message3
```

## Refactor explicit poroelasticity kernels

```
HASH4 message4
HASH5 message5
HASH6 message6
```

**Comment by rwalkerlewis** [comment]
I have no idea how, or rather i am concerned about causing harm. All i have managed thus far is to add another commit.

All of the changes could go into one commit, barring that, here we go:

# Refactor implicit poroelasticity kernels
To bdf350030819ece2d4a11dadf9f39df7654afe83 Poroelastic functions converted to inline
To  c282a10a6cec46bec223e1d76f27055d0dadd047 Added context for poroelasticity and isotropic linear poroelasticity
To 2b15335bb6616c5f62697873100ff30087ca9e15 Poroelastic fullscale tests compile and pass.

**Pull request merged**
