### PR TITLE
Feature multiple problem test

### PR DESCRIPTION
**Pull request by kali-allison**

### CODE REVIEW

**Comment by baagaard-usgs** [comment]
@kali-allison It looks like your `hackathon/earthquake-cycle branch` is out of sync with the `geodynamics:hackathon/earthquake-cycle` branch. 

https://github.com/kali-allison/pylith/tree/hackathon/earthquake-cycle shows
This branch is 3 commits ahead, 9 commits behind geodynamics:hackathon/earthquake-cycle.

See https://pylith.readthedocs.io/en/latest/developer/contributing/workflow.html#id3. Once you get your hackathon/earthquake-cycle branch in sync, you can rebase your feature-multiple-problem-test branch on your hackathon/earthquake-cycle branch.

**Comment by baagaard-usgs** [comment]
@kali-allison I think this PR may not be passing the tests because the changes to the top-level code require updates to the rest of the full-scale tests for them to pass.

Should I go ahead and merge this PR anyway?

**Comment by kali-allison** [comment]
@baagaard-usgs Are the required changes something small to make the input files for the tests compatible with my introduction of multiple problems? Maybe I should make those changes first.

**Comment by baagaard-usgs** [comment]
The updates to the other full-scale tests are simple (mostly just changing `pylithapp.problem` to `pylithapp.problems.problem` but I think we might need to address how to deal with specifying the application start and end time and individual problem start and end times before we update a bunch of files.

I suggest that we use the following logic. If there is only one problem, then the problem end time gets set to the application end time. If there is more than one problem, then (for now) we let the individual problem end times be set according to the .cfg settings. 

Try implementing this and updating the .cfg settings in the first full-scale tests that gets run in the test suite. These are the tests in `tests/fullscale/cornercases/2d`.

**Comment by kali-allison** [comment]
Right now I'm computing a problem duration for the second problem, rather
than using the start and end times explicitly. So for example, I set the
2nd problem to start at 0 and end at 2 years in independent.cfg, but then
in the code it runs for a total of 2 years, but starts with the end time of
the 1st problem and runs to the end time of the 1st problem + 2 years. Do
you want me to change that?

**Comment by baagaard-usgs** [comment]
When there is more than one problem, I would keep things as you have them. That is, use the duration based on the individual problem start and end times.

**Comment by kali-allison** [comment]
Ok, so I just need to modify the start and end times for single problems.

Is there a quick way to change pylithapp.problem to
pylithapp.problems.problem, or should I do it by hand?

**Comment by baagaard-usgs** [comment]
I think you have things setup to modify the problem start times based on the application time, so I think it is just setting the end time (when there is a single problem).

VS Code can search/replace through an entire project. However, I would start by doing search/replace in the cornercases/2d .cfg files manually -or- by writing a sed script to do it. Hopefully, this is the only change that is needed. If more changes are needed, then the sed script might make it easy to include all of the changes. If only the one change is needed, then VS Code search/replace should be easy.

**Comment by kali-allison** [comment]
How do I get the length of self.problems? Right now I'm looping over the
list of problems to print their start and end times, so I can count them
from that. But I don't think we want to keep that long term.

Also, I've gotten confused about this twice now. What's the difference
between these:
/opt/pylith/dest/debug/lib/python3.8/site-packages/pylith/apps/PyLithApp.py
/opt/pylith/src/pylith/pylith/apps/PyLithApp.py

**Comment by baagaard-usgs** [comment]
The files under `/opt/pylith/src/pylith` are the source files. The files under `/opt/pylith/dest/debug` are the "installed" files. Running `make` installs the files under source to the destination directory.

You can get the number of problems using `len(self.problems.components())`.

**Comment by kali-allison** [comment]
I've fixed my start and end time issues. I ended up needing to use this
block to update the problem start and end times:
problem.startTime = self.startTime
problem.endTime = self.endTime
problem.setStartTime(self.startTime.value)
problem.setEndTime(self.endTime.value)
problem.updateTimes()

I would've thought I'd only need lines 1+2 or 3+4 (plus line 5 in both
cases). But at least the rest of the logic in PyLithApp seems to be correct.

I'd like to move on to updating the other fullscale tests to change
pylithapp.problem to pylithapp.problems.problem, but I'm a little nervous
about breaking something. I tried making the changes in all the cfg files
in /opt/pylith/src/pylith/tests/fullscale/cornercases/2d, and then ran
"nemesis test_pylith.py" and got a ton of errors. Did that test work before
all my recent edits?

Thanks,
Kali

**Comment by baagaard-usgs** [comment]
Here is an explanation of what those lines of code do:

```python
# These two lines only update the time in the TimeDependent Python object
problem.startTime = self.startTime
problem.endTime = self.endTime

# These two lines update the start and end time values in the TimeDependent C++ object
problem.setStartTime(self.startTime.value)
problem.setEndTime(self.endTime.value)

# This routine takes the start and end times in the Time Dependent C++ object and updates the times in the PetscTS object
problem.updateTimes()
```

Clearly, this is too convoluted and we should clean it up. If we want consistent values for the start and end times in the Python, C++, and PetscTS objects, then we need all 5 lines of code. My recommendation is to add a method in the TimeDependent Python object called `updateStartEndTimes()` that takes the start and end times as arguments and executes these five lines of code. I would also change the TimeDependent C++ object method from `updateTimes()` to `updateTSTimes()`. You will need to update the corresponding name in the SWIG wrapper too.

Here is an outline of the Python code for `TimeDependent.py`:

```python
def updateStartEndTimes(self, startTime, endTime):
    self.startTime = startTime
    self.endTime = endTime

    ModuleTimeDependent.setStartTime(self, startTime.value)
    ModuleTimeDependent.setEndTime(self, endTime.value)
    ModuleTimeDependent.updateTSTimes(self)
```

The `fullscale/cornercases/2d` tests should run without errors. I will double check.

**Comment by kali-allison** [comment]
Thanks! I thought there must be some separation between the TimeDependent
Python object and the TimeDependent C++ object, but the way they work
together is not clear to me.

For fullscale/cornercases/2d, my guess is that I need to update a few more
things in the input files. A few questions:
1) Am I literally replacing pylithapp.problem with
pylithapp.problems.problem? In my test case
(fullscale/linearelasticity/eqcycle-2d) I have pylithapp.problems.timedependent
instead.

2) A closely related question. For each test, do I need to add something
equivalent to
[pylithapp]
problems = [rigidsliding]
as I have in fullscale/linearelasticity/eqcycle-2d/rigidsliding.cfg?

3) In rigidsliding_quad.cfg, I have
[pylithapp.problems.rigidsliding]
progress_monitor.filename = output/rigidsliding_quad-progress.txt
defaults.name = rigidsliding_quad

And in fullscale/cornercases/2d/axialdisp_quad.cfg I see
[pylithapp]
dump_parameters.filename = output/axialdisp_quad-parameters.json
problem.progress_monitor.filename = output/axialdisp_quad-progress.txt

Should I update that to
[pylithapp.problems]
dump_parameters.filename = output/axialdisp_quad-parameters.json
problem.progress_monitor.filename = output/axialdisp_quad-progress.txt

Unfortunately that's not so easy to do with a sed command...at any rate I
want to get 1 test corrected by hand before I try to write something to
automate (or, more likely, do a combination of automation and manual
changes) changing all the other tests.

**Comment by baagaard-usgs** [comment]
> 1. Am I literally replacing `pylithapp.problem` with `pylithapp.problems.problem`?

You can use either `pylithapp.problems.problem` or `pylithapp.problems.timedependent`. The Pyre framework allows aliases. In PyLithapp, we create `problems` with a default object of `SingleProblem`; `SingleProblem` is an object with a single problem called `problem` with a default object of `TimeDependent` (which has `timedependent` as an alias).

> 2. A closely related question. For each test, do I need to add something equivalent to
> 
> ```ini
> [pylithapp]
> problems = [rigidsliding]
> ```
> 

No. As I mentioned in my response to your first question, the default we create in PyLithApp.py + SingleProblem.py is equivalent to:

```ini
[pylithapp]
problems = [problem]
```

> 3. In rigidsliding_quad.cfg, I have
> 
> ```ini
> [pylithapp.problems.rigidsliding]
> progress_monitor.filename = output/rigidsliding_quad-progress.txt
> defaults.name = rigidsliding_quad
> ```
> 
> And in fullscale/cornercases/2d/axialdisp_quad.cfg I see
> 
> ```ini
> [pylithapp]
> dump_parameters.filename = output/axialdisp_quad-parameters.json
> problem.progress_monitor.filename = output/axialdisp_quad-progress.txt
> ```
> 
> Should I update that to
> 
> ```ini
> [pylithapp.problems]
> dump_parameters.filename = output/axialdisp_quad-parameters.json
> problem.progress_monitor.filename = output/axialdisp_quad-progress.txt
> ```
> 

PyLithApp still has `dump_parameters`, so the settings should look like

```ini
 [pylithapp]
dump_parameters.filename = output/axialdisp_quad-parameters.json
problems.problem.progress_monitor.filename = output/axialdisp_quad-progress.txt
```

**Comment by kali-allison** [comment]
Got it. I suspect my issue running cornercases/2d lies somewhere in
question 3 - I didn't realize I needed to change anything like that.

Another question: where should I be compiling the code? I've been doing it
from /opt/pylith/build/debug/pylith. But that has the effect of only seeing
changes to /opt/pylith/dest/debug/lib/python3.8/site-packages/pylith/apps/PyLithApp.py
and not /opt/pylith/src/pylith/pylith/apps/PyLithApp.py. So I must be doing
something wrong.

**Comment by baagaard-usgs** [comment]
You edit the code under `/opt/pylith/src/pylith`; we usually refer to this as the "source directory".

You build (run `make install`) in `/opt/pylith/build/debug`; we usually refer to this as the "build directory". This will "install" the code in `/opt/pylith/dest/debug`. For the C++ source code, "install" compiles the code and installs the shared libraries; for the SWIG code, "install" builds the modules and installs the Python modules; for the Python code, "install" copies and byte compiles the Python files.

When you want to run the tests, it is usually best to run them from under the "build directory". You can run the full-scale tests in the "source directory", but this pollutes the source tree with temporary files, so we rarely do this. To get the input files for the full-scale tests from the source tree to the build tree run `make export-data` in the build tree.

**Comment by kali-allison** [comment]
When I run make export-data in /opt/pylith/build/debug/pylith I get the
error:
make: *** No rule to make target 'export-data'.  Stop.

**Comment by baagaard-usgs** [comment]
`make export-data` only works in the full-scale test subdirectories like `cornercases/2d`. The general way to run tests from the top-level build directory or any subset in the directories under the `tests` build directory is to run `make check`. Sorry if I confused you.

**Comment by kali-allison** [comment]
Hmm. I'm definitely still doing something wrong. I made changes to
/opt/pylith/src/pylith/pylith/apps/PyLithApp.py
/opt/pylith/src/pylith/pylith/problems/TimeDependent.py
/opt/pylith/src/pylith/libsrc/pylith/problems/TimeDependent.cc
/opt/pylith/src/pylith/libsrc/pylith/problems/TimeDependent.hh
/opt/pylith/src/pylith/modulesrc/problems/TimeDependent.i

Then I tried make check in
/opt/pylith/build/debug/pylith/tests/fullscale/linearelasticity/eqcycle-2d
I get an error:
Traceback (most recent call last):
  File
"/opt/pylith/src/pylith/tests/fullscale/linearelasticity/eqcycle-2d/test_pylith.py",
line 18, in <module>
    from pylith.testing.FullTestApp import TestDriver, TestCase
ImportError: cannot import name 'TestCase' from
'pylith.testing.FullTestApp'
(/opt/pylith/dest/debug/lib/python3.8/site-packages/pylith/testing/FullTestApp.py)
FAIL test_pylith.py (exit status: 1)

I also tried
***@***.***:/opt/pylith/build/debug/pylith/tests/fullscale/linearelasticity/eqcycle-2d$
pylith independent.cfg independent_quad.cfg
Fatal error. Calling MPI_Abort() to abort PyLith application.
Traceback (most recent call last):
  File
"/opt/pylith/dest/debug/lib/python3.8/site-packages/pylith/apps/PetscApplication.py",
line 61, in onComputeNodes
    self.main(*args, **kwds)
  File
"/opt/pylith/dest/debug/lib/python3.8/site-packages/pylith/apps/PyLithApp.py",
line 154, in main
    problem.updateStartEndTimes(currStartTime,currEndTime)
AttributeError: 'TimeDependent' object has no attribute
'updateStartEndTimes'
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
/opt/pylith/dest/debug/bin/nemesis: mpiexec: exit 255
/opt/pylith/dest/debug/bin/pylith: /opt/pylith/dest/debug/bin/nemesis: exit
1

That's how I was running my test case to evaluate my changes. Perhaps
there's a problem with this approach. But to me it looks like the new
function I introduced isn't available in the build directory.

**Comment by baagaard-usgs** [comment]
Here are steps that I did to get the eqycle-2d test to run and pass:

1. I pulled PETSc knepley/pylith and rebuilt.
2. I pulled the main branch and hackathon/earthquake-cycle branches and rebase the hackathon/earthquake-cycle branch.
3. I then pulled your branch and rebased it on the hackathon/earthquake-cycle branch. I rebuilt and got the TestCase error.
4. I made the following change to `eqcycle-2d/test_pylith.py`:

```
diff --git a/tests/fullscale/linearelasticity/eqcycle-2d/test_pylith.py b/tests/fullscale/linearelasticity/eqcycle-2d/test_pylith.py
index 43d290f82..f1525c37a 100755
--- a/tests/fullscale/linearelasticity/eqcycle-2d/test_pylith.py
+++ b/tests/fullscale/linearelasticity/eqcycle-2d/test_pylith.py
@@ -15,7 +15,7 @@
 #
 # ======================================================================

-from pylith.testing.FullTestApp import TestDriver, TestCase
+from pylith.testing.FullTestApp import TestDriver, FullTestCase

 import unittest

@@ -44,7 +44,7 @@ class TestApp(TestDriver):

 # ----------------------------------------------------------------------
 if __name__ == '__main__':
-    TestCase.parse_args()
+    FullTestCase.parse_args()
     TestApp().main()
```

5.  I forced push your branch, so you will need to delete it, do `git fetch -p`, and then check it out again.

**Pull request merged**
