### PR TITLE
Removed youngs modulus and poisson ratio

### PR DESCRIPTION
**Pull request by rwalkerlewis**
As per last week's meeting.

### CODE REVIEW

**Review by baagaard-usgs — CHANGES_REQUESTED** [review]
There are still a lot of unused subfields in `AuxSubfieldsPoroelasticity.py`. Please remove the ones that are not used in C++.

**Comment by rwalkerlewis** [comment]
I'm afraid I don't see what you are talking about...only one remained, undrained bulk modulus.

**Comment by baagaard-usgs** [comment]
I don't see solid bulk modulus or fluid bulk modulus in the C++ auxiliary subfields.
https://github.com/geodynamics/pylith/blob/main/libsrc/pylith/materials/IsotropicLinearPoroelasticity.cc#L118

**Comment by rwalkerlewis** [comment]
Those are input parameters, used to generate the biot modulus.

**Comment by baagaard-usgs** [comment]
Values that appear in a spatial databases used as input to auxiliary subfields are not auxiliary subfields, so they are not included in AuxSubfieldsPoroelasticity. These subfields in the Python objects are used to specify the discretization. Notice we don't list Vp and Vs in AuxSubfieldsIsotropicLinearElasticity, we only list the bulk modulus and shear modulus.

**Comment by rwalkerlewis** [comment]
That should cover it

**Review by baagaard-usgs — APPROVED** [review]

**Comment by baagaard-usgs** [comment]
Closes #391

**Pull request closed without merging**
