### PR TITLE
Poroelastic example problems

### PR DESCRIPTION
**Pull request by rwalkerlewis**
Added documentation for poroelastic material and 2D magma chamber example.

### CODE REVIEW

**Review by baagaard-usgs — CHANGES_REQUESTED** [review]
1. Please remove the temporary files: `*.aux` `*.fls` `diagrams.pdf` `diagrams.svg`
2. Remove modifications to files in `strikeslip-2d/figs`
3. `examples/magma-2d`: It is fine to include both `quad` and `tri` mesh files, but only include parameter files for one. If you really want to show how to run with the other mesh, just use the command line argument to change the mesh file rather than including an additional parameter file.

**Comment by rwalkerlewis** [comment]
I think i addressed all the listed points.

**Comment by baagaard-usgs** [comment]
@rwalkerlewis I just did a force push to this branch to clean up the history and consolidate the commits.

There are still several pieces missing.  I don't want you to have to deal with reverted changes when rebasing, so I will attempt to get these fixes done tonight. **Please do not push to this branch**

## Examples

- [ ] Add README.md
- [ ] Add descriptive suffix to step01 and step02
- [ ] Update examples/Makefile to include `magma-2d`
- [ ] Update pylithapp.cfg (remove PETSc settings)
- [ ] Add comments to step01
- [ ] Add comments to step02

## Docs

- [ ] Add image of generated mesh
- [ ] Add list of features
- [ ] Add screenshots of solution
- [ ] Update step01
- [ ] Update step02

**Comment by baagaard-usgs** [comment]
@rwalkerlewis I just did a force push to this branch to clean up the history and consolidate the commits.

There are still several pieces missing.  I don't want you to have to deal with reverted changes when rebasing, so I will attempt to get these fixes done tonight. **Please do not push to this branch**

## Examples

- [ ] Add README.md
- [ ] Add descriptive suffix to step01 and step02
- [ ] Update examples/Makefile to include `magma-2d`
- [ ] Update pylithapp.cfg (remove PETSc settings)
- [ ] Add comments to step01
- [ ] Add comments to step02

## Docs

- [ ] Add image of generated mesh
- [ ] Add list of features
- [ ] Add screenshots of solution
- [ ] Update step01
- [ ] Update step02

**Review by baagaard-usgs — APPROVED** [review]
Fixed issues and finished implementing and documenting example.

**Pull request merged**
